### ISSUE TITLE
Log 1.20.1 Forge 47.2.7

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apothic-Attributes#19]
ApothicAttributes-1.20.1-1.2.1.jar

[00:55:07] [modloading-worker-0/WARN] [mixin/]: @Inject(@At("INVOKE")) Shift.BY=5 on attributeslib.mixins.json:client.ClientPacketListenerMixin from mod attributeslib::handler$bop000$attributeslib$apoth_postAttrChangedEvent exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[00:56:06] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: attributeslib:dodge

**Comment by Krimatoria** [comment]
Hi
> [00:58:41] [Render thread/WARN] [mixin/]: @ Inject(@ At("INVOKE")) Shift.BY=5 on attributeslib.mixins.json:client.ClientPacketListenerMixin from mod attributeslib::handler$bme000$attributeslib$apoth_postAttrChangedEvent exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

this warning is again in the latest version, but I do not know how critical it is.
ApothicAttributes-1.20.1-1.3.7.jar

**Comment by andrewsf** [comment]
Full error log w/ ApothicAttributes-1.20.1-1.3.7.jar is:

```
[modloading-worker-0/WARN] [mixin/]: @Inject(@At("INVOKE")) Shift.BY=5 on attributeslib.mixins.json:client.ClientPacketListenerMixin::handler$big000$apoth_postAttrChangedEvent exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 280: Insufficient maximum stack size.
	at org.objectweb.asm.tree.analysis@9.7.1/org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:290)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:717)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:686)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:640)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:610)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:525)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:335)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.preInject(CallbackInjector.java:429)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1348)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3329)
	at java.base/java.lang.Class.getDeclaredField(Class.java:2640)
	at TRANSFORMER/phosphophyllite@0.7.0-alpha.0.2/net.roguelogix.phosphophyllite.registry.Registry.<clinit>(Registry.java:60)
	at TRANSFORMER/phosphophyllite@0.7.0-alpha.0.2/net.roguelogix.phosphophyllite.Phosphophyllite.<init>(Phosphophyllite.java:45)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.3.33/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.33/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:126)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IndexOutOfBoundsException: Insufficient maximum stack size.
	at org.objectweb.asm.tree.analysis@9.7.1/org.objectweb.asm.tree.analysis.Frame.push(Frame.java:273)
	at org.objectweb.asm.tree.analysis@9.7.1/org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:326)
	at org.objectweb.asm.tree.analysis@9.7.1/org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:173)
	... 46 more
```

Note: the commit [0c87e57](https://github.com/Shadows-of-Fire/Apothic-Attributes/commit/0c87e576f0bd208b1e1d79031e02765520a694f2) added the same line to the JSON a second time

```
    "refmap": "${modid}.refmap.json",
    "maxShiftBy": 5,

/* ... */

    "maxShiftBy": 5
```


According to [this comment](https://github.com/Kitteh6660/DramaticDoors/issues/87#issuecomment-2138166588), "maxShiftBy" has to be declared in [the "injectors" object](https://github.com/SpongePowered/Cookbook/blob/193bec47ae8b5184bdb01db8a60cfd6f9bf640aa/Plugin/PluginMixinTest/src/main/resources/mixins.pluginmixintest.json#L11). That [seems right](https://github.com/SpongePowered/Mixin/blob/4053421aa10aaac6127d969028a29c94fe3054f6/src/main/java/org/spongepowered/asm/mixin/transformer/MixinConfig.java#L119) at a glance.
