### ISSUE TITLE
Not sure what's causing the frahs

### ISSUE THREAD

**Issue by VirdsEyeBiew** [Shadows-of-Fire/Apothic-Attributes#22]
[00:38:03] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Can't find attribute attributeslib:dodge_chance
Index: 3
Listeners:
0: HIGHEST
1: net.minecraftforge.eventbus.EventBus$$Lambda/0x00007f93848ac8a0@6d0bbf0b
2: HIGH
3: ASM: dev.shadowsoffire.attributeslib.impl.AttributeEvents@4f25fe82 dodge(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
4: NORMAL
5: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@77bf11bf onProjectileHit(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
6: ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents onProjectileImpact(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
7: ASM: class twilightforest.events.ToolEvents onEnderBowHit(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
8: ASM: class twilightforest.events.EntityEvents onParryProjectile(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
9: net.minecraftforge.eventbus.EventBus$$Lambda/0x00007f93848ac8a0@59de631e
10: ASM: dev.shadowsoffire.apotheosis.adventure.AdventureEvents@62a35250 impact(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
11: LOWEST
12: ASM: dev.shadowsoffire.attributeslib.impl.AttributeEvents@4f25fe82 fixMCF9370(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
13: ASM: class ovh.corail.tombstone.event.EventHandler onProjectileImpact(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
14: net.minecraftforge.eventbus.EventBus$$Lambda/0x00007f93848ac8a0@7107d84a
java.lang.IllegalArgumentException: Can't find attribute attributeslib:dodge_chance
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22260_(AttributeSupplier.java:21)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(AttributeSupplier.java:28)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.ai.attributes.AttributeMap.m_22181_(AttributeMap.java:76)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_21133_(LivingEntity.java:1835)
at TRANSFORMER/attributeslib@1.3.1/dev.shadowsoffire.attributeslib.impl.AttributeEvents.dodge(AttributeEvents.java:309)
at TRANSFORMER/attributeslib@1.3.1/dev.shadowsoffire.attributeslib.impl.__AttributeEvents_dodge_ProjectileImpactEvent.invoke(.dynamic)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at TRANSFORMER/forge@47.2.0/net.minecraftforge.event.ForgeEventFactory.onProjectileImpactResult(ForgeEventFactory.java:677)
at TRANSFORMER/forge@47.2.0/net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:685)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.projectile.AbstractHurtingProjectile.m_8119_(AbstractHurtingProjectile.java:68)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
at java.base/java.lang.Thread.run(Thread.java:1583)
[00:38:03] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:deathcounter.mixins.json:MinecraftServerAccessorMixin from mod deathcounter,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer from mod majruszlibrary,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess from mod dankstorage,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:vivecraft.mixins.json:server.MinecraftServerMixin from mod vivecraft,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixin from mod bclib,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixinLate from mod bclib,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinDedicatedServer from mod majruszlibrary,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin from mod lithostitched,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin from mod tombstone,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:deathcounter.mixins.json:MinecraftServerAccessorMixin from mod deathcounter,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer from mod majruszlibrary,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess from mod dankstorage,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:vivecraft.mixins.json:server.MinecraftServerMixin from mod vivecraft,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixin from mod bclib,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixinLate from mod bclib,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:deathcounter.mixins.json:MinecraftServerAccessorMixin from mod deathcounter,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer from mod majruszlibrary,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess from mod dankstorage,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:vivecraft.mixins.json:server.MinecraftServerMixin from mod vivecraft,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixin from mod bclib,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixinLate from mod bclib,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:deathcounter.mixins.json:MinecraftServerAccessorMixin from mod deathcounter,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer from mod majruszlibrary,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess from mod dankstorage,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:vivecraft.mixins.json:server.MinecraftServerMixin from mod vivecraft,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixin from mod bclib,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixinLate from mod bclib,pl:mixin:A,pl:connector_pre_launch:A}
at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: Can't find attribute attributeslib:dodge_chance
at net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22260_(AttributeSupplier.java:21) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A}
at net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(AttributeSupplier.java:28) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A}
at net.minecraft.world.entity.ai.attributes.AttributeMap.m_22181_(AttributeMap.java:76) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:attributeslib.mixins.json:AttributeMapMixin from mod attributeslib,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.world.entity.LivingEntity.m_21133_(LivingEntity.java:1835) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:connectormod:insertInjectionTarget,xf:fml:connectormod:updateItemUseStartTreshold,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:connectormod:insertInjectionTarget,xf:fml:connectormod:updateItemUseStartTreshold,pl:mixin:APP:bclib.mixins.common.json:elytra.LivingEntityMixin from mod bclib,pl:mixin:APP:betterend.mixins.common.json:LivingEntityMixin from mod betterend,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin from mod citadel,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin from mod modernfix,pl:mixin:APP:bagus_lib.mixins.json:LivingEntityMixin from mod bagus_lib,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker from mod apotheosis,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin from mod apotheosis,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity from mod apotheosis,pl:mixin:APP:cave_dweller.mixins.json:MixinLivingEntity from mod cave_dweller,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity from mod shetiphiancore,pl:mixin:APP:curios.mixins.json:MixinLivingEntity from mod curios,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin from mod attributeslib,pl:mixin:APP:fabric-entity-events-v1.mixins.json:LivingEntityMixin from mod fabric_entity_events_v1,pl:mixin:APP:fabric-entity-events-v1.mixins.json:elytra.LivingEntityMixin from mod fabric_entity_events_v1,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin from mod tombstone,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinLivingEntity from mod majruszlibrary,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity from mod caelus,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin from mod cofh_core,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin from mod ecologics,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor from mod netherportalfix,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity from mod bookshelf,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity from mod bookshelf,pl:mixin:APP:dummmmmmy-common.mixins.json:LivingEntityMixin from mod dummmmmmy,pl:mixin:APP:cataclysm.mixins.json:LivingEntityMixin from mod cataclysm,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:LivingEntityMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:mixins.artifacts.common.json:item.hurtsound.LivingEntityMixin from mod artifacts,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin from mod betterdeserttemples,pl:mixin:APP:friendsandfoes-common.mixins.json:BlazeLivingEntityMixin from mod friendsandfoes,pl:mixin:APP:nyfsspiders.mixins.json:LivingEntityMixin from mod nyfsspiders,pl:mixin:APP:alexscaves.mixins.json:LivingEntityMixin from mod alexscaves,pl:mixin:APP:mixins.irons_spellbooks.json:LivingEntityMixin from mod irons_spellbooks,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity from mod charmofundying,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin from mod obscure_api,pl:mixin:A,pl:connector_pre_launch:A}
at dev.shadowsoffire.attributeslib.impl.AttributeEvents.dodge(AttributeEvents.java:309) ~[ApothicAttributes-1.20.1-1.3.1.jar%23384!/:1.3.1] {re:mixin,re:classloading}
at dev.shadowsoffire.attributeslib.impl.__AttributeEvents_dodge_ProjectileImpactEvent.invoke(.dynamic) ~[ApothicAttributes-1.20.1-1.3.1.jar%23384!/:1.3.1] {re:classloading,pl:eventbus:B}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.event.ForgeEventFactory.onProjectileImpactResult(ForgeEventFactory.java:677) ~[forge-1.20.1-47.2.0-universal.jar%23652!/:?] {re:classloading}
at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:685) ~[forge-1.20.1-47.2.0-universal.jar%23652!/:?] {re:classloading}
at net.minecraft.world.entity.projectile.AbstractHurtingProjectile.m_8119_(AbstractHurtingProjectile.java:68) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:vivecraft.mixins.json:world.entity.projectile.AbstractHurtingProjectileMixin from mod vivecraft,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:majruszlibrary-common.mixins.json:IMixinServerLevel from mod majruszlibrary,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerLevel from mod majruszlibrary,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel from mod sereneseasons,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel from mod crafttweaker,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel from mod corgilib,pl:mixin:APP:betterend.mixins.common.json:ServerLevelMixin from mod betterend,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:bclib.mixins.common.json:ServerLevelMixin from mod bclib,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor from mod friendsandfoes,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin from mod friendsandfoes,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:LevelMixin from mod citadel,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel from mod sereneseasons,pl:mixin:APP:betterend.mixins.common.json:LevelMixin from mod betterend,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:AttachmentTargetsMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:WorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:majruszlibrary-common.mixins.json:IMixinServerLevel from mod majruszlibrary,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerLevel from mod majruszlibrary,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel from mod sereneseasons,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel from mod crafttweaker,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel from mod corgilib,pl:mixin:APP:betterend.mixins.common.json:ServerLevelMixin from mod betterend,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:bclib.mixins.common.json:ServerLevelMixin from mod bclib,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor from mod friendsandfoes,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin from mod friendsandfoes,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:classloading,pl:connector_pre_launch:A}
at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin from mod cupboard,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin from mod betterendisland,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:majruszlibrary-common.mixins.json:IMixinServerLevel from mod majruszlibrary,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerLevel from mod majruszlibrary,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel from mod sereneseasons,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel from mod crafttweaker,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel from mod corgilib,pl:mixin:APP:betterend.mixins.common.json:ServerLevelMixin from mod betterend,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:bclib.mixins.common.json:ServerLevelMixin from mod bclib,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor from mod friendsandfoes,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin from mod friendsandfoes,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins from mod betterendisland,pl:mixin:A,pl:connector_pre_launch:A}
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23647!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin from mod kubejs,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin from mod kubejs,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:deathcounter.mixins.json:MinecraftServerAccessorMixin from mod deathcounter,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer from mod majruszlibrary,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess from mod dankstorage,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:vivecraft.mixins.json:server.MinecraftServerMixin from mod vivecraft,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixin from mod bclib,pl:mixin:APP:together.mixins.common.json:MinecraftServerMixinLate from mod bclib,pl:mixin:A,pl:connector_pre_launch:A}
... 5 more
[00:38:03] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID eb7807d5-1f39-416b-aaee-22116449df08

**Comment by Shadows-of-Fire** [comment]
This is caused when an entity is present that does not properly register its attributes via EntityAttributeCreationEvent.

This is more common when bringing over fabric mods via connector - there's not much I can do about it.
