### ISSUE TITLE
[Bug] [1.20.1] ConcurrentModificationException

### ISSUE THREAD

**Issue by Sandriell** [Shadows-of-Fire/Apothic-Attributes#25]
Seeing the following error during loading.

```
[22:41:30] [main/INFO] [ne.mi.co.Co.attributeslib/COREMODLOG]: Patching EffectRenderingInventoryScreen#renderEffects
Exception in thread "Thread-1" java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.computeLaunchPluginTransformerSet(LaunchPluginHandler.java:68)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:64)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/modernfix@5.15.0+mc1.20.1/org.embeddedt.modernfix.forge.config.NightConfigWatchThrottler$1.values(NightConfigWatchThrottler.java:37)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:162)
```

**Full Log**: https://gist.github.com/Sandriell/16bd3306019a37d927365e7b089d572b

**Forge**: 47.2.17
**Mod**: ApothicAttributes-1.20.1-1.3.4

**Comment by Shadows-of-Fire** [comment]
That exception is unrelated to AA, as it is coming directly from FML.  AA's transformer just happens to be running at the same time (but a coremod cannot interface with the code throwing that error).

**Comment by Sandriell** [comment]
Ok thanks.

I know it is out of scope for you, but if you have any suggestions on how to track down that kind of error, I would appreciate it.
