### ISSUE TITLE
---- Minecraft Crash Report ---- Description: Feature placement at dev.shadowsoffire.apotheosis.adventure.gen.BossDungeonFeature.m_142674_(BossDungeonFeature.java:108) ~[Apotheosis-1.20.1-7.4.3.jar%23375!/:7.4.3]

### ISSUE THREAD

**Issue by komdreupau** [Shadows-of-Fire/Apothic-Attributes#45]
Hi is this a possible conflict with something from Blueprint, Upgrade Aquatic? at net.minecraft.world.level.levelgen.structure.StructurePiece.m_73407_(StructurePiece.java:349) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?] {re:mixin,re:classloading,pl:mixin:APP:blueprint.mixins.json:StructurePieceMixin,pl:mixin:A}
[crashlog#1.txt](https://github.com/user-attachments/files/17458427/1.txt)

**Comment by Shadows-of-Fire** [comment]
This looks to be caused by some kind of mixin to the structure code, and is not an apoth problem. The stacktrace points to a code path that can only generate horizontal states, and may never return up/down.
